# Generated by Django 4.1.6 on 2023-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
        ),
    ]
